### ISSUE TITLE
Cannot read properites of undefined (reading 'push')

### ISSUE THREAD

**Issue by eb2ai** [zoreet/habit-tracker#1]
I believe you can simply click on the day to mark a habit is done. I get the following.

This is from a sandboxed vault with only this plugin installed.
![image](https://github.com/zoreet/habit-tracker/assets/134644662/c2fc9ce1-ea63-4ab3-9055-4d618dca3fcb)

I like the idea here, I hope I can get it to work.

**Comment by zoreet** [comment]
Weird. I'm sure I tested it with empty habits before. Will try to reproduce and push a fix asap

**Comment by zoreet** [comment]
Pushed [1.0.1](https://github.com/zoreet/habit-tracker/releases/tag/1.0.1) Thanks for raising this bug @eb2ai 

Once you start using it pls share feedback on how I could make it better. Right now it's tailored to an audience of 1, but I'd love to make it into something that has a positive impact on people.

**Comment by zoreet** [comment]
Pushed [1.0.1](https://github.com/zoreet/habit-tracker/releases/tag/1.0.1) Thanks for raising this bug @eb2ai 

Once you start using it pls share feedback on how I could make it better. Right now it's tailored to an audience of 1, but I'd love to make it into something that has a positive impact on people.

**Comment by eb2ai** [comment]
Thanks! I just confirmed that it's working well. You have an audience of 2.

I really like this layout and the simplicity of the approach. I will share a few ideas as feature requests if that works for you.
