### ISSUE TITLE
[Feature request] Streaks per habit?

### ISSUE THREAD

**Issue by Burnor** [zoreet/habit-tracker#14]
Would it be possible, or of interest, to add a number somewhere that shows how long each habit's streak has been kept alive?

**Comment by zoreet** [comment]
Added in version 1.3.0 https://github.com/zoreet/habit-tracker/releases/tag/1.3.0

Please try it out and let me know what you think.

<img width="567" alt="Screenshot 2024-05-01 at 00 45 54" src="https://github.com/zoreet/habit-tracker/assets/668132/63e7ff63-47b2-4df1-8ccc-3e4f41ecdf4b">

Thanks for suggesting this 🙏
