### ISSUE TITLE
Spacing after habit and limit days displayed

### ISSUE THREAD

**Issue by vcdsc** [zoreet/habit-tracker#15]
Hi! Not so much an issue as 2 quick questions, if that is alright.

1) My listed habits are displaying a large space after:

![image](https://github.com/zoreet/habit-tracker/assets/117476319/88cd1ea3-8749-4584-a870-55056b93fe8d)

Any idea what might be causing it/how to remove it?

2) Is there a way to limit the number of days displayed? Say, display only the current week, rather than the last 21 days?

If you need any more details on the items above, just let me know. Thanks in advance for any help! :)

**Comment by zoreet** [comment]
The way it's currently coded the title of the habit takes up all the free space available. Can you tell me more about what theme are you using? or any custom CSS? how wide are the elements with class `cm-line`? Thanks

**Comment by zoreet** [comment]
Regarding the 2nd question see #3  I'm actively working on it, please follow any progress updates there.

**Comment by vcdsc** [comment]
> The way it's currently coded the title of the habit takes up all the free space available. Can you tell me more about what theme are you using? or any custom CSS? how wide are the elements with class `cm-line`? Thanks

Thanks for the quick reply! Ah, I see, that explains it. I am using the "Typewriter" theme, have not changed the default css provided by the theme itself.

**Comment by zoreet** [comment]
Cool. Will give it a try and add a more sensible max width

**Comment by zoreet** [comment]
Fixed with release [1.2.0](https://github.com/zoreet/habit-tracker/releases/tag/1.2.0)
