### ISSUE TITLE
Obsidian must be restarted to update "today"

### ISSUE THREAD

**Issue by middric** [zoreet/habit-tracker#18]
`DEFAULT_SETTINGS.lastDisplayedDate` is set when the plugin loads. By default its todays date via the `getTodayDate` function which is sensible default behaviour.

If you leave Obsidian open across days and leave this default behaviour then the chart is never updated to reflect the current date - you have to restart Obsidian to have it update.

DEFAULT_SETTINGS should perhaps be replaced with a `getDefaultSettings` function so that the value for lastDisplayedDate is re-evaluated each time its used by the loadSettings method?

**Comment by middric** [comment]
Had some time to create a PR for this!

**Comment by zoreet** [comment]
Thank you @middric 🎉
