### ISSUE TITLE
[BUG REPORT] days to shows failed to function and cause extreme long date to clutter the interface 

### ISSUE THREAD

**Issue by Ravenclawer** [zoreet/habit-tracker#21]
I‘m on Windows 11 
obsidian1.5.3 
![image](https://github.com/zoreet/habit-tracker/assets/73892411/22c95583-d556-4a0a-a86d-6937e01436b1)
![image](https://github.com/zoreet/habit-tracker/assets/73892411/7bc5a438-f392-48b9-930a-3ff8ed14960d)

**Comment by zoreet** [comment]
Hi @Ravenclawer 

The code is expecting daysToShow to be a number, not a string. This is my bad, I'll push a fix, in the meantime, if you change it to a number `"daysToShow": 6` it will work.

**Comment by zoreet** [comment]
Fixed with [1.2.1](https://github.com/zoreet/habit-tracker/releases/tag/1.2.1)
