### ISSUE TITLE
Single ticks not showing

### ISSUE THREAD

**Issue by holroy** [zoreet/habit-tracker#27]
I'm tracking the days I'm met my walking goal, but it doesn't show that I've met the goal on the 2024-03-08. The corresponding entries from that goal are as follows:

![image](https://github.com/zoreet/habit-tracker/assets/11348165/00b3ac53-3296-4bef-a74d-07bb776b3024)

But in my daily notes it displays as:

![image](https://github.com/zoreet/habit-tracker/assets/11348165/5ed110a5-dcc9-450a-823f-14dbbfa68f60)

It would be nice if just a single day also showed. :-D

**Comment by zoreet** [comment]
That's definitely a bug. Thanks for reporting. Will try an reproduce and get back to you

**Comment by zoreet** [comment]
I put in exactly the dates as you have them and unfortunately for me it works... This is just a hunch, but why do you know why the cells for 6, 10, and 12 are wider than the rest? I suspect there might be some CSS that just breaks for the 8th aka for solo days.

**Comment by holroy** [comment]
This was indeed a faulty CSS at my end, so sorry for the disturbance. I've now corrected the default values in the #25 , so that they'll show single day ticks as they should do.
