### ISSUE TITLE
Adjust the number of days shown

### ISSUE THREAD

**Issue by eb2ai** [zoreet/habit-tracker#3]
It would be nice to adjust the number of days displayed. This would be nice to show a full month or more.

I would suggest making it an option in the codeblock so it's easy to changed depending on where it's being used.
```habittracker
{
	"path": "Habits/",
	"days": "31"
}
```

**Comment by zoreet** [comment]
@eb2ai @xelaras right now the width of the page, at least in the default theme, doesn't allow more than 21 habits to be displayed. If the number goes up what would you expect to happen:
- horizontal scroll
- overflow: the box widens to the right and breaks out of the page width


https://github.com/zoreet/habit-tracker/assets/668132/d29413be-8cbe-4568-88b5-205d53df1cdb

I prefer scroll, but if you tell me you'd like for it to overflow I could add a setting to allow that too.

**Comment by xelaras** [comment]
I actually prefer the overflow version: it makes it possible to have the complete view of the entire month at a glance, and to count the number of times the habit was performed in the month.

(By the way, it would also be great to have the count directly after the name of the habit, in parentheses).

**Comment by zoreet** [comment]
I've heard you, so now with version [1.2.0](https://github.com/zoreet/habit-tracker/releases/tag/1.2.0) you can show as many dates as you want, and if there's not enough space the dates will overflow to the right. Please test it out and if you find anything funny let me know.
