### ISSUE TITLE
Tracker Pixel ????!

### ISSUE THREAD

**Issue by alayhi** [zoreet/habit-tracker#32]
really love the plugin but the tracking pixel is completely unneccessary - not even sure what use that data would be to you - please remove or at least be transparent that your collecting data - 

const trackingPixel = document.createElement("img");
        trackingPixel.setAttribute("src", "https://bit.ly/habitttracker21-140");
        el.parentElement.appendChild(trackingPixel);
        new HabitTracker(src, el, ctx, this.app);

**Comment by zoreet** [comment]
I realize I only mentioned it in the release notes but not in the readme, so I will update that, my bad. Thanks for pointing it out.

As to why:

I added it to track if people are actually using the tracker. There's not much point in investing time into something that people don't use. And yes, I see the number of downloads, but how many are on the latest version? If I see nobody updates it means they download it, try it, hate it and move on. This data shows me that I have roughly 100 active users/day, which is not too bad 😊 

Does that sound reasonable?

This is what I see.

<img width="1136" alt="Screenshot 2024-05-17 at 09 15 49" src="https://github.com/zoreet/habit-tracker/assets/668132/77c0c9d3-53dd-4720-b3e6-36675a9367f0">

<img width="1138" alt="Screenshot 2024-05-17 at 09 17 41" src="https://github.com/zoreet/habit-tracker/assets/668132/ab6c1bb9-97c7-4061-9aaf-20d791221dfe">

**Comment by zoreet** [comment]
Readme is up to date https://github.com/zoreet/habit-tracker/blob/master/README.md#tracking

**Comment by zoreet** [comment]
Please feel free to reopen this ticket and continue the conversation if needed.

**Comment by daikon-by** [comment]
Good day. Is it possible to add duplication of the column names at the end of the tracker, otherwise it is very inconvenient in the mobile version?

**Comment by Soluna7** [comment]
Hi! I've just started using this plugin, and I am incorporating it into my daily notes as I can already tell I will be using it a lot. It is a fantastic way to visualize the progress I've made on my various habits. However, I do have one very small aesthetic gripe, and I was wondering if there are any plans to be able to customize the color of the tracker? I primarily use Obsidian in light mode, and there the tracked days show up as an ugly burnt orange color that really clashes with my notes. I'd love to see an option to customize this color, or even (if feasible/reasonable), an option to have different custom colors for different habits (maybe a hex code parameter in the habit file?). 
![HabitTracker](https://github.com/user-attachments/assets/69ef29c6-e72e-49a7-a221-e04b0f619a2f)

**Comment by arnevr** [comment]
A very nice app that I use daily.
I've noticed that if I make an incorrect setting, the app reverts to the default settings. That's okay, but at the same time, it searches in my notes for the word "habit" and shows it as a daily habit. Is that the expected reaction?
