### ISSUE TITLE
Click on the name of the habit should bring you to the document

### ISSUE THREAD

**Issue by eb2ai** [zoreet/habit-tracker#4]
One of the reasons I love this approach is that information for my habit is contained within the document that contains the property list.

So, clicking on the habit name and opening the document would be very intuitive.

**Comment by eb2ai** [comment]
I hope you don't mind all the suggestions.

**Comment by zoreet** [comment]
Not at all, keep em coming. 

Regarding the click on the title: I agree 100%. I tried to do that before but failed. I had a quick look again and I think I solved it ( i needed to add a css class presumably for js to target it ). Will add it in soon
