### ISSUE TITLE
Creates multiple entries for a single habit on a same day when the file name contains "," comma in it

### ISSUE THREAD

**Issue by zuwf** [zoreet/habit-tracker#8]

**Comment by zuwf** [comment]
Also not recognise the habit when the file name contains "&" in it

**Comment by zoreet** [comment]
Nice one! I definitely didn't anticipate these use cases. Will look into it

**Comment by zoreet** [comment]
https://github.com/zoreet/habit-tracker/releases/tag/1.1.1
